title: "CYX的个人主页" 
author: "陈宇翔 Yx Chen" 
email: "chenyuxiang@zjut.edu.cn" 
description: "这是一个个人项目仓库" 
url: "https://CYX-1120.github.io" # 你的GitHub Pages URL 
github_username: "CYX-1120" # 你的GitHub用户名
